!--------------------------------------------------------------------------------------------------!
!   CP2K: A general program to perform molecular dynamics simulations                              !
!   Copyright 2000-2026 CP2K developers group <https://cp2k.org>                                   !
!                                                                                                  !
!   SPDX-License-Identifier: GPL-2.0-or-later                                                      !
!--------------------------------------------------------------------------------------------------!

MODULE trajana_cube_io
   USE trajana_kinds,                   ONLY: dp

   IMPLICIT NONE
   PRIVATE

   PUBLIC :: write_cube

CONTAINS

   SUBROUTINE write_cube(path, title, origin, spacing, dimensions, values, ierr, message)
      CHARACTER(LEN=*), INTENT(IN)                       :: path, title
      REAL(dp), INTENT(IN)                               :: origin(3), spacing, values(:)
      INTEGER, INTENT(IN)                                :: dimensions(3)
      INTEGER, INTENT(OUT)                               :: ierr
      CHARACTER(LEN=*), INTENT(OUT)                      :: message

      INTEGER                                            :: index, ix, iy, iz, unit, written
      REAL(dp), PARAMETER                                :: angstrom_to_bohr = 1.8897261246257702_dp

      ierr = 0
      message = ""
      IF (PRODUCT(dimensions) /= SIZE(values)) THEN
         ierr = 1
         message = "CUBE grid dimensions do not match the supplied data"
         RETURN
      END IF
      OPEN (NEWUNIT=unit, FILE=TRIM(path), STATUS="replace", ACTION="write", IOSTAT=ierr)
      IF (ierr /= 0) THEN
         message = "Cannot open CUBE output "//TRIM(path)
         RETURN
      END IF
      WRITE (unit, "(A)") TRIM(title)
      WRITE (unit, "(A)") "Generated by CP2K trajana; coordinates are in bohr"
      WRITE (unit, "(I5,3F13.6)") 1, origin*angstrom_to_bohr
      WRITE (unit, "(I5,3F13.6)") dimensions(1), spacing*angstrom_to_bohr, 0.0_dp, 0.0_dp
      WRITE (unit, "(I5,3F13.6)") dimensions(2), 0.0_dp, spacing*angstrom_to_bohr, 0.0_dp
      WRITE (unit, "(I5,3F13.6)") dimensions(3), 0.0_dp, 0.0_dp, spacing*angstrom_to_bohr
      WRITE (unit, "(I5,4F13.6)") 0, 0.0_dp, 0.0_dp, 0.0_dp, 0.0_dp
      written = 0
      DO ix = 1, dimensions(1)
         DO iy = 1, dimensions(2)
            DO iz = 1, dimensions(3)
               index = (ix - 1)*dimensions(2)*dimensions(3) + (iy - 1)*dimensions(3) + iz
               WRITE (unit, "(1X,ES13.5)", ADVANCE="no") values(index)
               written = written + 1
               IF (MOD(written, 6) == 0) WRITE (unit, "(A)") ""
            END DO
         END DO
      END DO
      IF (MOD(written, 6) /= 0) WRITE (unit, "(A)") ""
      CLOSE (unit)
   END SUBROUTINE write_cube

END MODULE trajana_cube_io
