specfile_path: tools/fedora/cp2k.spec
files_to_sync:
  - src: tools/fedora/
    dest: ./
    filters:
      - "- plans/main.fmf.dist-git"
  - src: tools/fedora/plans/main.fmf.dist-git
    dest: plans/main.fmf
  - src: .fmf/
    dest: .fmf/
  - .packit.yaml
upstream_package_name: cp2k
downstream_package_name: cp2k
update_release: false
upstream_tag_template: v{version}

jobs:
  - job: copr_build
    trigger: commit
    branch: master
    owner: lecris
    project: nightly
    additional_repos:
      - copr://@scikit-build/release
    targets:
      - fedora-all-x86_64
      - fedora-all-aarch64
  - job: tests
    trigger: commit
    targets:
      - fedora-all-x86_64
      - fedora-all-aarch64
  - job: copr_build
    trigger: release
    owner: lecris
    project: release
    targets:
      - fedora-all-x86_64
      - fedora-all-aarch64
  - job: copr_build
    trigger: pull_request
    manual_trigger: true
    owner: lecris
    project: cp2k
    update_release: true
    release_suffix: "{PACKIT_RPMSPEC_RELEASE}"
    targets:
      - fedora-all-x86_64
      - fedora-all-aarch64
  - job: tests
    trigger: pull_request
    manual_trigger: true
    targets:
      - fedora-all-x86_64
      - fedora-all-aarch64
  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-rawhide
  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all
  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched
