/*----------------------------------------------------------------------------*/
/*  CP2K: A general program to perform molecular dynamics simulations         */
/*  Copyright 2000-2026 CP2K developers group <https://cp2k.org>              */
/*                                                                            */
/*  SPDX-License-Identifier: BSD-3-Clause                                     */
/*----------------------------------------------------------------------------*/

/* SPDX-License-Identifier: BSD-3-Clause
 * Copyright (c) 2026 Susi Lehtola
 *
 * Generated by tools/gen_prime_table.py — do not edit by hand.
 *
 * Numeric ceilings for the prime table compiled into libwignernj.
 * Included by src/primes.h so every translation unit sees the
 * same constants.  Regenerate by running tools/gen_prime_table.py
 * after adjusting LIMIT in that script. */
#ifndef WIGNERNJ_PRIME_TABLE_MACROS_H
#define WIGNERNJ_PRIME_TABLE_MACROS_H

#define PRIME_SIEVE_LIMIT 20011
#define MAX_PRIME_COUNT 2263
#define MAX_FACTORIAL_ARG 20020

#endif /* WIGNERNJ_PRIME_TABLE_MACROS_H */
