#!/bin/bash

gcc -c -g -Wall -pedantic cp2k_c_bridge.c
if [[ $? ]]; then
 gcc -c -g -Wall -pedantic test.c
 if [[ $? ]]; then
  f95 -g -dryrun test.o cp2k_c_bridge.o -L/home/fawzi/cp2k/lib/Linux-i686-nag/sdbg/ -lcp2k_lib -lcp2k_base_lib -llapack
 fi
fi

