#!/bin/sh -v
rm -rf CP2K_INPUT.html index.html index_javascript.html references.html units.html generate_manual_howto.html CP2K_INPUT/ cp2k_input.xml
export FORT_C_NAME=g95
../../exe/Linux-x86-64-${FORT_C_NAME}/cp2k.popt --xml
./xml2htm
scp -r CP2K_INPUT.html index.html references.html units.html generate_manual_howto.html favicon.png CP2K_INPUT/ ${CP2KORG}public_html/manual/cp2k-2_1-branch
