#!/bin/sh
# Provide path to saxon
# Java version from http://sourceforge.net/projects/saxon
export SAXON=~/bin/saxon9he.jar
if [[ -z $1 ]]; then
   java -Xmx256m -jar $SAXON -o:index.html cp2k_input.xml cp2k_input.xsl add_edit_links=no
else
   java -Xmx256m -jar $SAXON -o:index.html cp2k_input.xml cp2k_input.xsl add_edit_links=no version=$1
fi
# Update the CP2K syntax file for the (g)vim editor
java -Xmx256m -jar $SAXON -o:cp2k.vim cp2k_input.xml vim.xsl
