= tblite-run(1)
Sebastian Ehlert (@awvwgk)
:doctype: manpage

== Name
tblite-run - Run tight-binding calculations

== Synopsis
*tblite run* [_options_] _input_


== Description

Evaluates the tight-binding model on the provided input structure.
Periodic calculations are performed automatically for periodic input formats.
Reads .CHRG and .UHF files if present in the same directory as the input.

Supported geometry input formats are:

- Xmol/xyz files (xyz, log)
- Turbomole's coord, riper's periodic coord (tmol, coord)
- DFTB+ genFormat geometry inputs as cluster, supercell or fractional (gen)
- VASP's POSCAR/CONTCAR input files (vasp, poscar, contcar)
- Protein Database files, only single files (pdb)
- Connection table files, molfile (mol) and structure data format (sdf)
- Gaussian's external program input (ein)


== Options

*-c, --charge* _integer_::
     Set charge to molecule,
     overrides charge in .CHRG file

*--spin* _integer_::
     Set number of unpaired electrons for molecule,
     overrides spin in .UHF file

*--method* _string_::
     Name of the parametrisation to use, supported are
     _gfn1_, _ipea1_, _gfn2_ (default), and _gxtb_.

*--param* _string_::
     Read tight binding parametrization from _string_.

*--etemp* _real_::
     Electronic temperature for calculation in Kelvin (default: 300K).

*--guess* _string_::
     Guess for the initial populations, possible options:
     _sad_ (default), _eeq_, _eeqbc_ (default for g-xTB), and _ceh_.

*--restart* [_string_]::
     Restart calculation from previous run.
     Provide the name of the restart file (default 'tblite-restart.npz')

*--no-restart*::
     Do not restart from previous run.

*--etemp-guess* _real_::
     Electronic temperature for ceh-guess in Kelvin (default: 4000K).

*--efield* _real_,_real_,_real_::
     Homogeneous electric field in V/Å, takes three comma separated real values.

*--alpb* _string_::
     Use analytical linearized Poisson-Boltzmann (ALPB) solvation model.
     Solvent is specified by the solvent name.
     Uses parametrized ALPB with CDS and empirical shift.

*--gbsa* _string_::
     Use generalized Born solvation model (GBSA).
     Solvent is specified by the solvent name.
     Uses parametrized GB with CDS and empirical shift.

*--gbe* _real_|_string_::
     Use generalized Born with finite epsilion (GBSA) solvation model.
     Solvent is specified by dielectric constant or the solvent name.

*--gb* _real_|_string_::
     Use generalized Born solvation model (GB).
     Solvent is specified by dielectric constant or solvent name.

*--cpcm* _real_|_string_::
     Use polarizable continuum solvation model (CPCM).
     Solvent is specified by dielectric constant or solvent name.

*--born-kernel* _string_::
     Specify Born kernel to use with ALPB, GBSA or GB solvation model.
     Possible options are _p16_ (default for ALPB) and _still_ (default for GB/GBSA).

*--solv-state* _string_::
     Solution state correction: _gsolv_ (default), _bar1mol_, _reference_.

*--spin-polarized*::
     Use spin-polarized Hamiltonian with colinear spins.
     **Important**: This feature is not stable and results are subject to change.

*--acc* _real_::
     Accuracy of the calculation,
     lower values set tighter convergence criteria.

*--iterations* _int_::
     Number of iterations for converging the electronic structure.
     Default: 250.

*--broyden-start* _int_::
     Iteration to start the Broyden mixer.
     Default: 0.

*--diis-start* _int_::
     Iteration to start the DIIS mixer.
     Default: 0.

*--solver* _name_::
     Electronic solver for SCF, possible options:
     _gvd_ (default), and _gvr_

*--grad* [_file_]::
     Evaluates analytical gradient,
     results are stored in _file_ (default: tblite.txt)

*--post-processing* _file_|_name_::
     Add post processing methods to the calculation either by using a toml file as input
     or by specifying the post-processing step name directly.
     Mayer-Wiberg bond orders are computed by default.
     - molmom (molecular multipole moments)
     - xtbml (atomistic properties based on Mulliken partitioning)

*--post-processing-output* _file_::
     Output file for post processing results in npz format.
     (default: tblite-data.npz)

*--json* [_file_]::
     Dump results as JSON output to _file_ (default: tblite.json)

*-i, --input* _format_::
     Hint for the format of the input file

*-v, --verbose*::
     Increase verbosity of printout

*-s, --silent*::
     Reduce verbosity of printout

*--version*::
     Prints version number and citation

*--help*::
     Show this message


Command line arguments can be read from an indirect file / response file by specifying the file with @_name_ in the command line.
Each line in the file is interpreted as command line argument, shell like escape sequences are not available.
The file can contain further @_name_ inputs. If the file cannot be the argument is used literally.


== See also

*tblite*(1)
