= tblite-guess(1)
Sebastian Ehlert (@awvwgk)
:doctype: manpage

== Name
tblite-guess - Run an atomic charge model.

== Synopsis
*tblite guess* [_options_] _input_


== Description

Evaluates the atomic charge model on the provided input structure.
Reads .CHRG and .UHF files if present in the same directory as the input.

Supported geometry input formats are:

- Xmol/xyz files (xyz, log)
- Turbomole's coord, riper's periodic coord (tmol, coord)
- DFTB+ genFormat geometry inputs as cluster, supercell or fractional (gen)
- VASP's POSCAR/CONTCAR input files (vasp, poscar, contcar)
- Protein Database files, only single files (pdb)
- Connection table files, molfile (mol) and structure data format (sdf)
- Gaussian's external program input (ein)


== Options

*-c, --charge* _integer_::
     Set charge to molecule,
     overrides charge in .CHRG file

*--spin* _integer_::
     Set number of unpaired electrons for molecule,
     overrides spin in .UHF file

*--method* _string_::
     Name of the atomic charge model to use, supported are
     sad, eeq, eeqbc, and ceh (Charge-Extended Hückel method, default)

*--etemp-guess* _real_::
     Electronic temperature for ceh-guess in Kelvin (default: 4000K).

*--solver* _name_::
     Electronic solver for charge model, possible options:
     _gvd_ (default), and _gvr_

*--efield* _real_,_real_,_real_::
     Homogeneous electric field in V/Å, takes three comma separated real values.

*--grad* [_file_]::
     Evaluates analytical gradient of the charges.

*-i, --input* _format_::
     Hint for the format of the input file

*-v, --verbose*::
     Increase verbosity of printout

*-s, --silent*::
     Reduce verbosity of printout

*--version*::
     Prints version number and citation

*--help*::
     Show this message


Command line arguments can be read from an indirect file / response file by specifying the file with @_name_ in the command line.
Each line in the file is interpreted as command line argument, shell like escape sequences are not available.
The file can contain further @_name_ inputs. If the file cannot be the argument is used literally.


== See also

*tblite*(1)
