= tblite-param(1)
Sebastian Ehlert (@awvwgk)
:doctype: manpage

== Name
tblite-param - Export, import and manipulate tight-binding parameter files

== Synopsis
*tblite param* [_options_] _input_


== Description

Allows to export parameter files from the internal storage or merge parameter files with an internal base parametrization.
The _input_ variable must be present or an internal parametrization should be selected.


== Options

*--output* _string_::
     Output file to write parameters

*--method* _string_::
     Name of the parametrisation to use, supported are
     _gfn1_, _ipea1_ and _gfn2_

*--version*::
     Prints version number and citation

*--help*::
     Show this message


Command line arguments can be read from an indirect file / response file by specifying the file with @_name_ in the command line.
Each line in the file is interpreted as command line argument, shell like escape sequences are not available.
The file can contain further @_name_ inputs. If the file cannot be the argument is used literally.


== See also

*tblite*(1)
