[check]
line-length = 132
force-exclude = true

# Also see https://fortitude.readthedocs.io/en/stable/rules
ignore = [
    "non-standard-file-extension",
    "implicit-external-procedures", # requires Fortran 2018
    "missing-intent",
    "bad-quote-string",
    "literal-kind",
    "assumed-size",
    "assumed-size-character-intent",
    "interface-implicit-typing",
    "missing-default-case",
    "external-procedure",
    "trailing-backslash",
]

# ==============================================================================
# The following files can not be parsed by Fortitude.
# Usually because Fortran statements are inter-leafed with pre-processor macros.
exclude = [
    "local_gemm_api.F",
    "smeagol_control_types.F",
    "ai_contraction_sphi.F",
    "qs_loc_states.F",
    "dbt_array_list_methods.F",
    "cp_cfm_basic_linalg.F",
    "cp_cfm_diag.F",
    "cp_fm_basic_linalg.F",
    "cp_fm_cholesky.F",
    "cp_fm_diag.F",
    "message_passing.F",
    "dbt_split.F",
    "cp_cfm_cholesky.F",
    "pw_methods.F",
    "xc_libxc_wrap.F",
    "dbt_tas_util.F",
]

# ==============================================================================
[check.per-file-ignores]
"environment.F" = ["line-too-long"]
"libgint_wrapper.F" = ["trailing-backslash"]
"qs_block_davidson_types.F" = ["trailing-backslash"]
"qs_linres_current.F" = ["trailing-backslash"]
"qs_local_properties.F" = ["unreachable-statement"]
"qs_tddfpt2_subgroups.F" = ["trailing-backslash"]
"semi_empirical_int_ana.F" = ["misleading-inline-if-semicolon"]
"pilaenv_hack.F" = ["procedure-not-in-module"]
"semi_empirical_int_debug.F" = ["procedure-not-in-module"]
"eri_mme_lattice_summation.F" = ["trailing-whitespace"]
"gopt_f77_methods.F" = ["procedure-not-in-module"]
"fftw3_lib.F" = ["misleading-inline-if-semicolon"]

#EOF
