include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - deps
  - cp2k
  - test

variables:
  REPOSITORY: cp2k_eiger
  BUILDER: spack
  VERSION: ssmp
  TAG: "${BUILDER}_${VERSION}"
  UBUNTU_IMAGE_NAME: "ubuntu:24.04"
  CSCS_IMAGE_NAME: "${CSCS_REGISTRY_PATH}/${REPOSITORY}:${TAG}_${CI_COMMIT_SHORT_SHA}"
  DOCKERHUB_IMAGE_NAME: "docker.io/${DOCKERHUB_USERNAME}/${REPOSITORY}:${TAG}"

build deps eiger:
  extends: .container-builder-cscs-zen2
  stage: deps
  timeout: 1h
  before_script:
    - DEPS_IMAGE_TAG=`cat ci/cscs_eiger_${TAG}.yaml ci/docker/build_${CI_JOB_STAGE}_${BUILDER}.Dockerfile $(find tools/spack -type f) $(find cmake -type f) | sha256sum - | head -c 16`
    - export PERSIST_IMAGE_NAME=${CSCS_REGISTRY_PATH}/base/${REPOSITORY}:${TAG}_${DEPS_IMAGE_TAG}
    - echo "DEPS_IMAGE_NAME=${PERSIST_IMAGE_NAME}" | tee build.env
  artifacts:
    reports:
      dotenv: build.env
  variables:
    DOCKER_BUILD_ARGS: '[
      "BASE_IMAGE",
      "CP2K_BUILD_TYPE",
      "CP2K_VERSION",
      "LOG_LINES"
    ]'
    DOCKERFILE: ci/docker/build_${CI_JOB_STAGE}_${BUILDER}.Dockerfile
    BASE_IMAGE: ${UBUNTU_IMAGE_NAME}
    CP2K_BUILD_TYPE: all
    CP2K_VERSION: ${VERSION}
    LOG_LINES: 200

build cp2k eiger:
  extends: .container-builder-cscs-zen2
  stage: cp2k
  needs: ["build deps eiger"]
  timeout: 1h
  before_script:
    - echo ${DOCKERHUB_TOKEN} | podman login docker.io --username ${DOCKERHUB_USERNAME} --password-stdin
  after_script:
    - podman images
    - podman push ${PERSIST_IMAGE_NAME} ${DOCKERHUB_IMAGE_NAME}
  variables:
    DOCKER_BUILD_ARGS: '[
      "BASE_IMAGE",
      "DEPS_IMAGE"
    ]'
    DOCKERFILE: ci/docker/build_${CI_JOB_STAGE}_${BUILDER}.Dockerfile
    BASE_IMAGE: ${UBUNTU_IMAGE_NAME}
    DEPS_IMAGE: ${DEPS_IMAGE_NAME}
    PERSIST_IMAGE_NAME: ${CSCS_IMAGE_NAME}

test cp2k eiger:
  extends: .baremetal-runner-eiger-zen2
  stage: test
  needs: ["build cp2k eiger"]
  timeout: 1h
  script:
    - podman run --env OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK} --shm-size=1g -v ${PWD}:/mnt ${DOCKERHUB_IMAGE_NAME} cp2k /opt/cp2k/benchmarks/CI/H2O-32_md.inp
  variables:
    SLURM_CONSTRAINT: mc
    SLURM_CPUS_PER_TASK: 8
    SLURM_DEBUG: 1
    SLURM_HINT: nomultithread
    SLURM_JOB_NUM_NODES: 1
    SLURM_NTASKS: 1
    SLURM_NTASKS_PER_NODE: 1
    SLURM_TIMELIMIT: 10

regression test cp2k eiger:
  extends: .baremetal-runner-eiger-zen2
  stage: test
  needs: ["build cp2k eiger","test cp2k eiger"]
  timeout: 1h
  script:
    - git --no-pager log -1 --pretty="%nCommitSHA:%x20%H%nCommitTime:%x20%ci%nCommitAuthor:%x20%an%nCommitSubject:%x20%s%n"
    - podman run --shm-size=1g -v ${PWD}:/mnt ${DOCKERHUB_IMAGE_NAME} /opt/cp2k/tests/do_regtest.py --maxtasks ${SLURM_NTASKS} --mpiexec "mpiexec -bind-to none" --keepalive /opt/cp2k/bin ${VERSION} 2>&1 || true
  variables:
    SLURM_CONSTRAINT: mc
    SLURM_DEBUG: 1
    SLURM_HINT: nomultithread
    SLURM_JOB_NUM_NODES: 1
    SLURM_NTASKS: 128
    SLURM_TIMELIMIT: 30

# EOF
