" Vim syntax file
" Language: cp2k input files
" Maintainer: based on work by Alin M Elena available at https://gitorious.org/cp2k-vim
" Latest Revision: 13th of September 2010

if exists("b:current_syntax")
  finish
endif

syn case ignore

"----------------------------------------------------------------/
"       cp2k predefined constants
"----------------------------------------------------------------/

" extracted from the file generated by cp2k.popt --xml using
" grep -A 1  "<ITEM>" cp2k_input.xml | grep NAME | sed 's;<NAME>;;g' | sed 's;<\/NAME>;;g' | tr -d [:blank:] | tr '[:upper:]' '[:lower:]' | sort | uniq | xargs | fold -s -c -w 120 | sed -e 's/.*/syn keyword cp2kConstant &/'; echo
syn keyword cp2kConstant 1-1 1-2 120 1-3 1-4 147 1s 2p 2pnt 2s 3pnt 3point 3point_2d 407 93 ac ad add ad_langevin all almo_scf alpha am1 amber 
syn keyword cp2kConstant analytic analytical arnoldi aspc atom atomic atoms automatic b3lyp b97grimme b97_grimme band basis_optimization 
syn keyword cp2kConstant basis_projection bazant becke becke88x becke_constraint berry beta bfgs bfgs_hess bisect blas block_count 
syn keyword cp2kConstant block_density_matrix blocked block_lmax block_surface blyp b-neb box boys bp broyden broyden_mixing broyden_mixing_new 
syn keyword cp2kConstant bsse buffer calc_matrix cauchy cauchy_subspace cell_opt cg charge charmm chm chol cif ci-neb cn coac coefficients 
syn keyword cp2kConstant collocate column com common complex_4 complex_8 conjugate_gradient constant constraint contracted_gto copy core coulomb 
syn keyword cp2kConstant coupled covalent cp2k crazy crd csvr cube cubic cuda dai_yuan davidson dcd ddapc ddapc_constraint ddiag debug default 
syn keyword cp2kConstant defined dens densities density dftb dftd2 dftd3 diag diagonal_analytical diagonal_numerical diff diis dimer dipole 
syn keyword cp2kConstant direct direct_canonical direct_cell_opt direct_p_mixing distributed dkh dkh(0) dkh(1) dkh(2) dkh(3) dkh(4) dkh(5) dmc 
syn keyword cp2kConstant d-neb drsll dsatur dscf dx2 dxy dy2 dyz dz2 dzx eb edip ehrenfest_dyn eip electronic_spectra elpa em energy 
syn keyword cp2kConstant energy_force energy_window ep equal_a equal_f erfc estimate etrs ev93 ewald ewald_gks ewald_r3 exhaustive 
syn keyword cp2kConstant explicit_orbitals exponents false farming fe fermi_dirac fftsg fftw fftw3 fist fit fix_point fletcher fletcher_reeves 
syn keyword cp2kConstant force_matching free frozen fues full full_all full_kinetic full_single full_single_inverse full_s_inverse function 
syn keyword cp2kConstant functional g87 g96 gapw gapw_xc gauss gaussian gc_log gc_simple gc_transformed gemc_npt gemc_nvt general generate 
syn keyword cp2kConstant genmix geo_center geometrical_gto geometry_optimization geo_opt gho glb gle gllb global global_opt gold gpw greedy grid 
syn keyword cp2kConstant gth hager_zhang harmonic hartree-fock hcth120 hestenes_stiefel hexagonal high high-spin history_restart hotelling 
syn keyword cp2kConstant hydrostaticshock identity imomm interleaved inverse inverse_cholesky irac isokin iterative it-neb jacobi kdso kdso-d 
syn keyword cp2kConstant kerker_mixing kohn-sham l1sd lanczos langevin lb lb94 lb_alpha lbfgs lc length lenosky linear_combination linear_p 
syn keyword cp2kConstant linear_ps linear_response linear_wf list liu_storey llp lmkll longrange low lowdin lr lripaw lwdn mass massive master 
syn keyword cp2kConstant matmul mauri_spz mauri_us mc mc_analysis mcy3 md me measure medium metadyn minima_crawling minima_hopping minimization 
syn keyword cp2kConstant minimum mix_cl mix_cl_trunc mixed mixed_bend_stretch mix_lg mm2 mm3 mm4 mndo mndod mo_diag molden_restart molecular 
syn keyword cp2kConstant molecular_dynamics molecule mol_set monoclinic mo_no_diag montecarlo mopac morse mos mp mp2_gpw msst msst_damped mt 
syn keyword cp2kConstant mulliken mulliken_charges multipole multisecant_mixing new nn10 nn10_smooth nn4 nn4_smooth nn50 nn50_smooth nn6 
syn keyword cp2kConstant nn6_smooth no none non_local normal normal_modes nose no_shortcut npe_f npe_i npt_f npt_i ns-fullspace ns-halfspace 
syn keyword cp2kConstant numeric numerical nve nvt nvt_adiabatic occupied octahedron off ofgpw ol1 ol2 old olyp on optimize_basis optimize_input 
syn keyword cp2kConstant optimize_ri_basis optx orig original orthorhombic ot pade pair_potential patient pbe pbe0 pbesol pbex pcg pdb pdg 
syn keyword cp2kConstant perfect_balance periodic pint pipek plasma pm3 pm6 pme pnnl polak_ribiere poly ps pseudo pseudopotential_optimization 
syn keyword cp2kConstant psf pulay_mixing pw pw86 pw86x pw91 pw91x px py pz qm qmmm qs quadratic quadrupole quartic quickstep r ramp random 
syn keyword cp2kConstant r_and_step_function read real_4 real_8 reduce reflective reftraj remove replicated restart restart_vec restart_wfn 
syn keyword cp2kConstant restore restraint revpbe rev_pbex rhf rhombohedral ri_mp2_gpw ri_rpa_gpw ri_sos_laplace rks rm1 rohf row rt_propagation 
syn keyword cp2kConstant rt_restart rvv10 s s2_constraint sainv same_as_particle saop scf scf_r scf_wfn scmp scp scptb sczora(mp) sd 
syn keyword cp2kConstant self_consistent semi_analytic shortrange sic sign_matrix sign_sqrt silent singlet singlets s_ks sl sl2 slater sm 
syn keyword cp2kConstant smallest_maximum smm soe sparse sparse_diag sparse_kinetic sparse_stable_approximate_inverse spectra spherical spin 
syn keyword cp2kConstant spl3_nopbc_aint1 spl3_nopbc_aint2 spl3_nopbc_precond1 spl3_nopbc_precond2 spl3_nopbc_precond3 spline2 spline2_smooth 
syn keyword cp2kConstant spline3 spline3_nopbc spline3_smooth spme spreadmax spreadmin square stage standard strict sum_eigenvalues swarm s-wave 
syn keyword cp2kConstant syevd syevx symbolic t t92 tamc taylor tddfpt tdlr test test_lsd tetragonal tetragonal_ab tetragonal_ac tetragonal_bc 
syn keyword cp2kConstant tmc tp_fh tp_hh tpss tp_val tp_xfh tp_xhh traditional transition_state triclinic triplet triplets trs4 true truncated 
syn keyword cp2kConstant tshpsc uhf ui uks undefined unit unoccupied unpaired upsf use_guess use_prev_p use_prev_rho_r use_prev_wf user 
syn keyword cp2kConstant user_defined vdw vector velocity vibrational_analysis virial vmc vwn3 vwn5 wall_minus wall_plus wannier wavefunction 
syn keyword cp2kConstant wavefunction_optimization wavelet weight_list wfn wfn_opt x -x xc_functional xmol x_r xsc x_then_scf xtl xy xyz xz y -y 
syn keyword cp2kConstant yz z -z zero zora zora(mp)

"----------------------------------------------------------------/
"       cp2k sections
"----------------------------------------------------------------/
" grep -A1 -i "<Section" cp2k_input.xml | grep NAME | sed 's;<NAME>;;g' | sed 's;<\/NAME>;;g' | tr -d [:blank:] | tr '[:upper:]' '[:lower:]' | sort | uniq | xargs | fold -s -c -w 120 | sed -e 's/.*/syn keyword cp2kSection &/'; echo
syn keyword cp2kSection 2d_mc 2pnt accepts add_mm_charge adiabatic_dynamics adiabatic_rescaling ad_langevin ae_basis alchemical_change almo_scf 
syn keyword cp2kSection alpha angle angle_plane_plane angles ao_matrices atom atomic atomic_coordinates atom_list 
syn keyword cp2kSection auxiliary_density_matrix_method avbmc averages band banner barostat basis basis_molopt_quantities basis_set beads 
syn keyword cp2kSection becke88 becke88_lr becke88_lr_adiabatic becke97 becke_restraint becke_restraint_a becke_restraint_b becke_roussel bend 
syn keyword cp2kSection beta bfgs block block_density_matrix_method bmhft bmhftd bond bond_rotation bonds box_displacements box_probabilities 
syn keyword cp2kSection bs bsse buck4ranges buckmorse buffer_links buffer_non_adaptive cascade cell cell_opt cell_ref center center_coordinates 
syn keyword cp2kSection center_of_mass centroid_gyr centroid_pos centroid_vel cg charge charges chebyshev check_spline chi chi_tensor ci_neb 
syn keyword cp2kSection cls_function_cubes coefficients collective colvar colvar_func_info colvar_restart com combine_colvar communication_log 
syn keyword cp2kSection compare_energies compare_forces conditioned_distance configuration constant_env constrain_exponents constraint 
syn keyword cp2kSection constraint_info control convergence_control convergence_info conv_info coord coord_avg coord_fit_points coordinates 
syn keyword cp2kSection coordination coord_var core_coord core_forces core_trajectory core_velocities core_velocity coulomb count coupling 
syn keyword cp2kSection cp_dbcsr cp_fm_gemm cs1 csvr cube_data cubes cuda current current_cubes curvy_steps damping davidson dbcsr 
syn keyword cp2kSection ddapc_restraint ddapc_restraint_a ddapc_restraint_b debug define_region density_fitting derivatives derived_basis_sets 
syn keyword cp2kSection detailed_energy dft dftb dft_control_parameters dft_plus_u diagonalization diag_sub_scf diis diis_info dimer 
syn keyword cp2kSection dimer_vector dipole dipoles direct_canonical displaced_atom distance distance_from_path distance_function 
syn keyword cp2kSection distance_point_plane distribution distribution1d distribution2d dos dump_pdb dump_psf each eam e_density_cube efield 
syn keyword cp2kSection efield_cube eigensolver eip electric_field_gradient elf_cube energies energies_minus_kinetic energies_var energy 
syn keyword cp2kSection enforce_occupation ep ep_matrixes epr ep_rho_cube et_coupling ewald ewald_info exchange exclude_ei_list 
syn keyword cp2kSection exclude_vdw_list external_density external_potential external_vxc ext_lagrange_fs ext_lagrange_ss ext_lagrange_ss0 
syn keyword cp2kSection ext_lagrange_vvp ext_restart farming ff_info ff_parameter_file fit_basis fit_charge fit_density fit_kind fit_pseudo 
syn keyword cp2kSection fix_atom_restart fixed_atoms flexible_partitioning force force_eval force_eval_mixed forcefield force_matching 
syn keyword cp2kSection force_mixing force_mixing_labels forces forces_inst fragment fragment_energies frame free_energy free_energy_info g3x3 
syn keyword cp2kSection g4x6 ga gapw gaussian gaussian_env geminal geminal_basis generate generic genpot geo_opt gle global global_opt gold 
syn keyword cp2kSection goodwin grid_information g_tensor gth_potential gv09 gyration_radius harris hbonds hbp hcth helium hf hf_info hfx_ri 
syn keyword cp2kSection hills history hydronium hyperfine_coupling_tensor image_charge image_charge_info image_charge_restart improper 
syn keyword cp2kSection impropers init interaction_potential interatomic_distances interpolator involved_atoms ipbv isolated_atoms 
syn keyword cp2kSection iteration_info iter_info job ke_gga ke_libxc kg_method kind kinds kinetic_energy k_matrix krylov lagrange_multipliers 
syn keyword cp2kSection lanczos langevin lbfgs lda_hole_t_c_lr ldos lennard-jones libxc linear line_search link linres load_balance localize 
syn keyword cp2kSection loc_restart lowdin low_spin_roks lr_correction ls_scf lyp lyp_adiabatic machine_arch map mapping mass master_run_info 
syn keyword cp2kSection max_displacements mc md memory merge_molecules metadyn metavar method method_info mgrid minima_crawling minima_hopping 
syn keyword cp2kSection mixed mixed_energies mixing mm mm_kind mm_potential mo mo_cubes mode_selective molden_vib mol_displacements 
syn keyword cp2kSection molecular_dipoles molecular_states molecule molecules mol_probabilities mol_set mo_magnitude moments mo_orthonormality 
syn keyword cp2kSection motion move_mm_charge move_probabilities move_type move_updates mp2_info m-sampling msd msd_kind msd_molecule 
syn keyword cp2kSection ms_restart msst mt mulliken mulliken_restraint multiple_force_evals multiple_walkers multipole multipoles 
syn keyword cp2kSection nablavks_cubes <nametype=default>section_parameters neighbor_lists nmc_moves nmr nonbonded nonbonded14 non_local 
syn keyword cp2kSection nonperiodic_sys normalmode nose opbend optical_conductivity optimization optimize_band optimize_basis optimize_geminals 
syn keyword cp2kSection optimize_input opt_ri_basis optx orbitals ot outer_scf p86c pade pair_potential parameter pbe pbe_hole_t_c_lr pdos 
syn keyword cp2kSection periodic periodic_efield periodic_info periodic_sys perm pgf pint plane plength plus_u point poisson polar polar_matrix 
syn keyword cp2kSection population potential powell pp_basis print print_averages print_dftd print_specific_e_density_cube program_banner 
syn keyword cp2kSection program_run_info projectors properties pw92 pw_transfer pz81 qm_kind qmmm qmmm_charges qmmm_link_info qmmm_matrix 
syn keyword cp2kSection qm_non_adaptive qparm qs qs_derivatives quadratic quadrupole quadrupoles quartic radii ramp_env rdf reaction_path 
syn keyword cp2kSection real_time_propagation references reflective reftraj relativistic replica replica_info rescale_forces resp respa 
syn keyword cp2kSection resp_charges_to_file response_basis response_function_cubes restart restart_averages restart_history restart_info 
syn keyword cp2kSection restraint rho rho0_information ri_laplace ri_mp2 ring_puckering ri_rpa r_ldos rmsd rng_init rng_state rotational_info 
syn keyword cp2kSection rot_opt rs_grid rs_pw_transfer run_info s s2_restraint saop scf scf_info scptb screening scrf sdensity se shell 
syn keyword cp2kSection shell_coord shell_energy shell_forces shell_opt shell_trajectory shell_velocities shell_velocity shielding_tensor sic 
syn keyword cp2kSection siepmann smear spawned_hills_height spawned_hills_invdt spawned_hills_pos spawned_hills_scale sphere spinspin 
syn keyword cp2kSection spl_coeffs spline staging stm stress stress_tensor string_method structure_data subcell subsys swarm symmetry tddfpt 
syn keyword cp2kSection temp_control temperature temperature_colvar temp_kind temp_shell_kind tersoff test tf tfw thermal_region thermostat 
syn keyword cp2kSection thermostat_energy thermostat_fast thermostat_info thermostat_slow timings tmc tmc_analysis tmc_analysis_files topology 
syn keyword cp2kSection topology_info torsion torsions total_densities total_dipole total_numbers tot_density_cube tpss training_files 
syn keyword cp2kSection trajectory transition_state translation_vector u ub umbrella_integration update upf_file uvar variable vdw_potential 
syn keyword cp2kSection vel_control velocities velocity velocity_softening v_hartree_cube vibrational_analysis virtual_site v_resp_cube vwn 
syn keyword cp2kSection v_xc_cube walkers_file_name wall walls wannier_centers wannier_cubes wannier_spreads wannier_states wavelet wc weights 
syn keyword cp2kSection wfc_gpw wf_correlation wfn_mix williams wnumber worker_run_info xalpha xas xas_spectrum xc xc_functional xc_grid 
syn keyword cp2kSection xc_potential xes_spectrum xgga xray_diffraction_spectrum xwpbe xyz_diag xyz_outerdiag zmp

"----------------------------------------------------------------/
"       cp2k keywords
"----------------------------------------------------------------/
"grep -A1 -i "<Keyword" cp2k_input.xml | grep NAME | sed 's;<NAME\s*type="default">;;g' | sed 's;<\/NAME>;;g' | tr -d [:blank:] | tr '[:upper:]' '[:lower:]' | sort | uniq | xargs | fold -s -c -w 120 | sed -e 's/.*/syn keyword cp2kKeyword &/'; echo
syn keyword cp2kKeyword 2d_molecular_distribution a a1 a2 abc absolute_position accuracy acquisition_start_time activate 
syn keyword cp2kKeyword adaptive_exclude_molecules added_mos add_last admm_purification_method aint_precond algorithm align_frames a_list all 
syn keyword cp2kKeyword all_conf_file_name alltoall_sgl almo_scf alpha alpha0_hard alpha_1 alpha_2 alpha_beta_gamma alpha_imomm alpha_scp 
syn keyword cp2kKeyword always_checksum amber_info analytical_gradients analytical_gterm angle angle_tolerance angvel_tol angvel_zero annealing 
syn keyword cp2kKeyword annealing_cell apol append apply_delta_pulse a_scale asparsity aspc_order atom atom_coef atom_coordination_numbers 
syn keyword cp2kKeyword atomic_number atom_index_1 atom_index_2 atom_list atomparm atom_point atoms atoms_distance atoms_from atoms_list 
syn keyword cp2kKeyword atoms_lu_bounds atoms_plane atoms_to atoms_to_b atom_type at_per_mol atype autogen_exclude_lists 
syn keyword cp2kKeyword aux_basis_fit_normalization aux_basis_normalization aux_basis_set aux_fit_basis_set avbmc_atom avbmc_rmax avbmc_rmin 
syn keyword cp2kKeyword avealpha avebeta avecell_a avecell_b avecell_c ave_colvars avecpu ave_econs avegamma avehugoniot avekin avekin_qm 
syn keyword cp2kKeyword ave_mmatrix avepot ave_press ave_pv_cnstr ave_pv_fock_4c ave_pv_kin ave_pv_tot ave_pv_vir ave_pv_xc ave_pxx 
syn keyword cp2kKeyword average_colvar avetemp avetemp_baro avetemp_qm avevol avoid_after_busy axis b b1 b2 backup_copies band band_type 
syn keyword cp2kKeyword basic_data_types basic_optimization basic_spatial_optimization basis_combinations basis_normalization basis_output_file 
syn keyword cp2kKeyword basis_projection basis_set basis_set_file_name basis_template_file basis_type basis_work_file bcsr_code bd behavior 
syn keyword cp2kKeyword beta beta_1 beta_2 beta_3 bias bigd bigr big_send bij binary_restart_file_name binning_binsize binning_nbins bisection 
syn keyword cp2kKeyword bisect_trust_count blacs_grid blacs_repeatable blocked_eps_iter blocked_max_iter blocked_n_diis block_size bond 
syn keyword cp2kKeyword bondlength_max bondlength_min bondparm bondparm_factor boundaries box2_file_name brack_limit brent_max_iter brent_tol 
syn keyword cp2kKeyword broyden_adaptive_sigma broyden_beta broyden_enable_flip broyden_eta broyden_forget_history broyden_gamma broyden_omega 
syn keyword cp2kKeyword broyden_sigma broyden_sigma_decrease broyden_sigma_min broy_w0 broy_wmax broy_wref bs_k bs_m bs_n bsparsity bsse btype 
syn keyword cp2kKeyword bump_steps_downwards bump_steps_upwards c calc_cond_num calculate_c9_term calculate_states callgraph 
syn keyword cp2kKeyword callgraph_file_name cartesian cb cell_file cell_file_format cell_file_name cell_opt cell_shape cell_size center_point 
syn keyword cp2kKeyword central_atom centroid_speed charge charge_beta charge_extended charge_occup check_bcsr_code check_diis check_mos_conv 
syn keyword cp2kKeyword check_symmetry chi_pbc cholesky cif_info cij classical_dipole_moments clebsch_gordon c_list cmass coarse_grained_points 
syn keyword cp2kKeyword coarse_grained_width coeff coefficient col_block collective coloring_method colvar colvar_avg_temperature_restart 
syn keyword cp2kKeyword combined_types commensurate common_center common_iteration_levels comm_thread_load comp_input component component_a 
syn keyword cp2kKeyword component_b components components_to_fix compress comvel_tol condition_number condition_weight confinement 
syn keyword cp2kKeyword conn_file_format conn_file_name constraint_init __control_val convergence conv_mos_percent coord_file_format 
syn keyword cp2kKeyword coord_file_name coordinate coordinate_file_name coordinates coordination_cutoff copy core core_charge core_charge_radii 
syn keyword cp2kKeyword core_charges_radii core_correction core_hamiltonian core_ppl corr_radius cost_model coulomb_integrals 
syn keyword cp2kKeyword coupling_parameter cpol crazy_scale crazy_use_diag crd_info create_molecules cs csparsity ctype cube_eval_range 
syn keyword cp2kKeyword cubes_list cubes_lu_bounds custom_path cutoff cutoff_radius cycle cycles d d3_scaling damping data_file_name data_type 
syn keyword cp2kKeyword dc debug debug_forces debug_stress_tensor define_fragments def_type delocalize_algorithm delocalize_conjugator 
syn keyword cp2kKeyword delocalize_eps_iter delocalize_eps_lin_search delocalize_max_iter delocalize_method delocalize_r_cutoff_factor delta 
syn keyword cp2kKeyword delta_charge delta_i_rel delta_pulse_direction delta_pulse_scale delta_ri delta_t density density_cutoff 
syn keyword cp2kKeyword density_smooth_cutoff_range dependencies derivatives determ_coeff deterministic deviation d_exponents dgemm diag_method 
syn keyword cp2kKeyword dihedral_angle diis_buffer_length dipole_analysis dipole_file dipole_form direction directories directory 
syn keyword cp2kKeyword disable_exclusion_lists discrete_step dispersion dispersion_parameter_file dispersion_radius displaced_atom 
syn keyword cp2kKeyword displacement_shell_tol displacement_tol distance distances distances_rmsd distribution_layout distribution_type 
syn keyword cp2kKeyword dkh_order dm do_dso do_ewald do_fc do_hills do_nonbonded do_pso do_raman do_restart do_scc do_scp do_sd dot_tree 
syn keyword cp2kKeyword d_quantum_numbers dr drop_unused_envs dt dx dynamic_threshold e e0_only e_accept_init echo_all_hosts echo_input 
syn keyword cp2kKeyword econs_start_val e_coupl efg eigenvalues eigenvectors eip_model ei_scale14 elec_conf electron_configuration 
syn keyword cp2kKeyword electronic_temperature element emax_accuracy emax_spline enable_unsupported_features end_elem end_step end_step_in 
syn keyword cp2kKeyword end_step_out energies energy energy_file_name energy_function energy_gap energy_precision energy_range energy_scaling 
syn keyword cp2kKeyword energy_weight ensemble envelop ep_lin_solver eps eps_3c_reduce eps_adapt eps_adapt_scf eps_added eps_cn eps_conv 
syn keyword cp2kKeyword eps_core_charge eps_cpc eps_default eps_deriv eps_diis eps_disp eps_eigenvalue eps_eigval eps_ene eps_fermi_dirac 
syn keyword cp2kKeyword eps_filter eps_filter_matrix epsfit eps_geo eps_grid eps_gvg_rspace epsilon eps_irac eps_irac_filter_matrix 
syn keyword cp2kKeyword eps_irac_quick_exit eps_irac_switch epsiso eps_iter eps_jacobi eps_kg_orb eps_krylov eps_lanczos eps_lin_solv 
syn keyword cp2kKeyword eps_localization eps_lumo eps_max_val eps_mm_rspace eps_no_error_check eps_norm eps_occupation eps_optimization eps_out 
syn keyword cp2kKeyword eps_pgf_orb eps_pol eps_ppl eps_ppnl eps_r eps_rho epsrho0 eps_rho_gspace eps_rho_rspace eps_scf eps_scf_history 
syn keyword cp2kKeyword eps_schwarz eps_schwarz_forces eps_screening eps_skip_sub_diag eps_spline eps_std_diag eps_storage eps_storage_scaling 
syn keyword cp2kKeyword epssvd eps_taylor eps_u_ramping eps_x equal_charges erange eri error_limit escape_history_length esimate_acc_prob eta 
syn keyword cp2kKeyword e_target eval_energy_forces ewald_accuracy ewald_precision ewald_type exchange_integrals excitations exclude_ei 
syn keyword cp2kKeyword exclude_mm exclude_qm exclude_vdw exp_accuracy exp_pre extended_delta_charge extended_fft_lengths external_pressure 
syn keyword cp2kKeyword ext_potential extrapolation extrapolation_order f f0 fermi_amaldi fermi_contact f_exponents fft fft_pool_scratch_limit 
syn keyword cp2kKeyword fftw_plan_type fftw_wisdom_file_name file_density filename file_restart file_vxc filter_eps filter_factor 
syn keyword cp2kKeyword filter_factor_scale fingerprint_precision first_prec first_snapshot fist_scale_factor fix_centroid_pos fixed 
syn keyword cp2kKeyword fixed_magnetic_moment fixed_mu fletcher_reeves flush_should_flush force_blocksize force_env_file force_eval_order 
syn keyword cp2kKeyword force_kdso-d_exchange force_last force_paw force_rescaling format f_quantum_numbers fraction fragmentation_threshold 
syn keyword cp2kKeyword frame_count frame_start frame_stop frame_stride frequency fully_periodic function functional functional_form 
syn keyword cp2kKeyword functional_model functional_routine functional_type g96_info gamma gapw_max_alpha gapw_prj_radii gauge 
syn keyword cp2kKeyword gauge_atom_radius gcut geminal_basis_set geminal_file_name generate_info geo_check geometrical_factor geo_opt 
syn keyword cp2kKeyword geo_start_value ghost glb_conf global_gaussian_rng gmax gold_target gpw_type g_r gradient_cutoff grid grid_2d 
syn keyword cp2kKeyword grid_points grid_spacing grid_tol group_anlysis_nr group_cc_size group_energy_nr group_energy_size group_partition 
syn keyword cp2kKeyword group_size gspace_smoothing gth_ppl_radii gth_ppnl_radii gtop_info h halo_reduction_factor halo_size hard_exp_radius 
syn keyword cp2kKeyword harris_energy hb_sr_gamma helium_only hfx_balance_in_core hill_tail_cutoff hpm hydrogens ignore_missing_critical_params 
syn keyword cp2kKeyword image_restart_file_name indices inertia info_out_step_size init_acc_prob initial_configuration_info 
syn keyword cp2kKeyword initial_degrees_of_freedom initial_guess initial_step initial_translation_vector initial_wfn init_method 
syn keyword cp2kKeyword init_u_ramping_each_scf inner_atoms inner_radius inorot input_file_name integer_total_charge integral_screening 
syn keyword cp2kKeyword intensities intensity interaction_radius intermolecular interpolate_gradient interpolate_shift interpolation invert_s 
syn keyword cp2kKeyword involved_atoms ions+centers iprint irac_degree irot i_scp issc_on_atom_list iteration iter_start_val itimes_start 
syn keyword cp2kKeyword iuptrans iupvolume iweight j jacobi_fallback jacobi_threshold job_id just_energy k k2_spring k4_spring kbs12 kbs32 
syn keyword cp2kKeyword k_confidence_limit keep_angles keepsparse keep_symmetry kerker_min kernel kernel_file_name kg_method kind 
syn keyword cp2kKeyword kind_coordination_numbers kind_radii kinds kinds_from kinds_to kinds_to_b kinetic_energy kohn_sham_matrix k_rho 
syn keyword cp2kKeyword k_spring kss l label labels laddn0 lagrange lambda lambda1 lambda2 lambda3 langevin last_snapshot lbias ldiscrete 
syn keyword cp2kKeyword lebedev_grid length level_shift levy_correlated levy_pos_sample levy_seed levy_temp_factor linesearch line_search 
syn keyword cp2kKeyword link_type linmin_grad_only lin_solv list list_unoccupied lmax lmaxn0 lmaxn1 load_balance_info lochomo_restart_file_name 
syn keyword cp2kKeyword lock_distribution loclumo_restart_file_name log_print_key long_range_correction lri_basis_set lsd_singlets ls_scf lstop 
syn keyword cp2kKeyword m magnetic map map_atoms map_consistent mark_states mass mass_fraction master_slave mat_exp matmul matrix_cluster_type 
syn keyword cp2kKeyword matrix_vxc max_allowed_step max_angular_momentum max_coarse_grained_width max_crazy_angle max_diis max_disk_space 
syn keyword cp2kKeyword max_disp_file_name max_distance max_distributed_level max_dr max_elements_per_block max_energy max_force max_f_per_iter 
syn keyword cp2kKeyword max_fun max_gvec_exp max_h_rank max_ipol_iter max_irac max_iter max_iter_added max_iter_lanczos max_iter_lumo 
syn keyword cp2kKeyword max_jobs_per_group max_kv max_memory max_moment max_multipole_expansion max_n_qm max_perm_cycle maxr max_rad_local 
syn keyword cp2kKeyword max_scf max_scf_history max_sd_steps max_steep_steps maxstep max_step max_steps max_stepsize max_taylor 
syn keyword cp2kKeyword max_var_fraction mc md md_bumps_max memory memory_factor memory_progression_factor mem_pol metadynamics method 
syn keyword cp2kKeyword method_type min_disp min_energy min_filter min_flop_process min_flop_sort min_hessian_shift minimizer min_nt_hills 
syn keyword cp2kKeyword min_or_max min_radius mixed_precision mixing_fraction mixing_function mixing_type mm_atom_list mm_driver mm_index 
syn keyword cp2kKeyword mm_potential_file_name mm_radius mm_stack_size mm_subsys modefactor mo_index_range mol_check molecule 
syn keyword cp2kKeyword molecules_file_name molname momentum_conservation_region momentum_conservation_type mo_s_inv move_center_of_mass moves 
syn keyword cp2kKeyword moves_file_name mpi mpi_reordering m-ratio msd_per_kind msd_per_molkind msd_per_region mts mu multigrid_cutoff 
syn keyword cp2kKeyword multigrid_set multiple_potential multiple_subsys multiple_unit_cell multiplicity multrec_limit m-value n n0 natoms 
syn keyword cp2kKeyword n_bch_history nbeads nbin nbins nblock nbox nbuffer ncells n_chebyshev ncol_block nd nd_b ndigits n_diis ndim 
syn keyword cp2kKeyword neighbor_lists_from_scratch nel nequil_steps nev new_prec_each ngauss n_gridpoints ngrids ngroups nh nhills_start_val 
syn keyword cp2kKeyword n_history_vec nhomo nics nics_file_name nkrylov n_loop nlumo nmc_file_name nmixing nmol nmoves nn nn_b nnos nocenter 
syn keyword cp2kKeyword nocenter0 nocompatibility noisy_gamma no_ls nondiag_energy nondiag_energy_strength no_optimize normal_vector 
syn keyword cp2kKeyword nose_particle np_ls npoints nproc nproc_rep nreortho nrespa n_resp_fast nr_nmc_steps nrow_block nr_temperature 
syn keyword cp2kKeyword n_simple_mix n_size_mnk_stacks nskip ns_max nstep nsteps_it nswapmoves nt_hills number_of_atoms number_of_replica 
syn keyword cp2kKeyword number_of_shells number_of_walkers number_of_workers num_env num_gauss num_gto num_mc_elem num_mv_elem_in_cell 
syn keyword cp2kKeyword num_slater num_steps nvirial occupation_numbers occupation_preconditioner oce_hard oce_soft oe_corr old_hill_number 
syn keyword cp2kKeyword old_hill_step omega on_the_fly_loc operator optimize_end_points optimize_file_name optimizer opt_target opt_type 
syn keyword cp2kKeyword orbital_center orbitals orbital_set order orig_is_virtual orig_marked_state orig_mo_index orig_scale orig_spin_index 
syn keyword cp2kKeyword ortho orthogonal_basis ortho_irac o_spline out_each_mo outer_atoms outer_radius out_iter_each output_file_name overlap 
syn keyword cp2kKeyword overwrite_mos oxygens p p1_bond1 p1_bond2 p2_bond1 p2_bond2 pair_cutoff parallel_scheme parameter parameter_file_name 
syn keyword cp2kKeyword parameters parameter_set parametrization param_file_name param_file_path para_res parm_file_name parmtype pbc pbias 
syn keyword cp2kKeyword pdb_info perform_mu_scan periodic p_exponent p_exponents pfactor pgf_radii phase phi0 physcon pint_unit 
syn keyword cp2kKeyword plumed_input_file plus_u_method pmavbmc pmavbmc_mol pmhmc pmhmc_box pmrot_mol pmswap pmswap_mol pmtraion pmtraion_mol 
syn keyword cp2kKeyword pmtrans pmtrans_mol pmvol_box pmvolume pnh pno poisson_solver polarisation pol_scf poly1 poly2 position position_file 
syn keyword cp2kKeyword position_scaled posterior_buffers posterior_streams potential potential_energy potential_file_name potential_name 
syn keyword cp2kKeyword potential_type pot_type powell_opt p_quantum_numbers precond preconditioner precond_solver preferred_diag_library 
syn keyword cp2kKeyword preferred_fft_library prefix_ana_files presample pressure pressure_tolerance print_all print_branch print_cell 
syn keyword cp2kKeyword print_coords print_dipole print_energies print_forces print_full print_gop print_level print_only_acc print_proc 
syn keyword cp2kKeyword print_resume print_test_output print_thread print_thread_cur priority_buffers priority_streams prob proc_dist_type 
syn keyword cp2kKeyword process process_inhomogenous proc_per_replica program_name progression_factor project_name proj_velocity_verlet 
syn keyword cp2kKeyword propagator p_screen_correction_factor pseudo_type psf_info psi0 psi0_blocks psi1 pso pulay_alpha pulay_beta 
syn keyword cp2kKeyword purification purification_method pw_grid pw_grid_blocked pw_grid_layout pw_grid_layout_all pw_hfx pw_hfx_blocksize q 
syn keyword cp2kKeyword q_bead q_centroid q_end q_exponent q_max qm_extended_seed_is_only_core_list qm_index qm_kind qm_kind_element_mapping 
syn keyword cp2kKeyword qmmm_scale_factor qm_subsys qnh qno qs_scf quadrature quadrature_points r0 r012 r032 r0_b r0_nb r1 r2 r3 radial_grid 
syn keyword cp2kKeyword radii radius randomize randomize_pos randomize_variables random_number_generator randomtoskip range r_buf r_core 
syn keyword cp2kKeyword rcov_multiplication rc_range rc_taper rcut rcut_nb r_cutoff realspace reduction_factor reduction_steps ref0_filename 
syn keyword cp2kKeyword ref_cell_file_name ref_energy reference reference_c9_term reference_functional reference_point reference_set 
syn keyword cp2kKeyword ref_force_file_name ref_traj_file_name region regularization relativistic relax_multiplicity rel_cutoff 
syn keyword cp2kKeyword remove_contraction remove_set reorder replay_communication_log replica replica_eval report_all_sparsities res_etype 
syn keyword cp2kKeyword residuum_weight restart restart_averages restart_band restart_barostat restart_barostat_thermostat restart_bsse 
syn keyword cp2kKeyword restart_cell restart_constraint restart_core_pos restart_core_velocity restart_counters restart_current restart_default 
syn keyword cp2kKeyword restart_dimer restart_epr restart_every restart_file_name restart_helium_densities restart_helium_force 
syn keyword cp2kKeyword restart_helium_permutation restart_helium_pos restart_helium_rng restart_hessian restart_image_matrix restart_in 
syn keyword cp2kKeyword restart_limit restart_metadynamics restart_nmr restart_optimize_input_variables restart_out restart_pint_gle 
syn keyword cp2kKeyword restart_pint_nose restart_pint_pos restart_pint_vel restart_pos restart_qmmm restart_randomg restart_read restart_rtp 
syn keyword cp2kKeyword restarts restart_shell_pos restart_shell_thermostat restart_shell_velocity restart_spinspin restart_thermostat 
syn keyword cp2kKeyword restart_vel restart_walkers restart_write restrain_heavies_strength restrain_heavies_to_zero restraint_strength 
syn keyword cp2kKeyword restraint_target result_list_in_memory result_marked_state result_mo_index result_scale result_spin_index r_factor rho0 
syn keyword cp2kKeyword rho0_exp_radius rho1 ri_aux_basis_set rmangle rmax rmax_kind rmbond rmdihedral rmin rmin_kind rmrot rmsd rms_dr 
syn keyword cp2kKeyword rms_force rmtrans rmvolume rnd_deterministic rng_check rng_matrices roh roks roks_f roks_parameters roks_scheme 
syn keyword cp2kKeyword roll_tolerance roo __root__ rotate rotate_frames rotation rotation_matrices rot_opt row_block row_major r_qm rs2pw 
syn keyword cp2kKeyword run_type sab_aux_fit sab_aux_fit_vs_orb sab_cn sab_core sab_lrc sab_orb sab_orb_full sab_orb_molecular sab_scp sab_se 
syn keyword cp2kKeyword sab_tbe sab_vdw sac_ae sac_ppl safe_computation safe_diis sap_oce sap_ppnl save_mem scale scale_c scale_coulomb scaled 
syn keyword cp2kKeyword scale_gaussian scale_longrange scale_s scale_t scale_temp_kind scale_x scale_x0 scaling sc_check_start scf_guess 
syn keyword cp2kKeyword scf_optimizer scf_type sched_mpi sched_thread scp scp_nddo screen_on_initial_p screen_p_forces sd_like seed 
syn keyword cp2kKeyword selected_states_atom_radius selected_states_on_atom_list self_consistent se_parameters se_p_orbitals_on_h set_radii 
syn keyword cp2kKeyword s_exponents shadow_gamma shake_tolerance share_history shell_charge shell_cutoff shell_opt shift shift_average 
syn keyword cp2kKeyword shift_cutoff shift_gapw_radius shift_mm shift_qm sic_method sic_scaling_a sic_scaling_b sigma sign_sqrt_order 
syn keyword cp2kKeyword single_precision_matrices s_inversion sip_list size size_freq_integ_group size_integ_group sk_file 
syn keyword cp2kKeyword skip_load_balance_distributed skip_optimization slow_growth smear smoothing smooth_width soo_list soo_rho_hard 
syn keyword cp2kKeyword sort_by_self_time sparse_mos speculative_canceling spherical_cutoff spherical_harmonics spin_configuration spline_data 
syn keyword cp2kKeyword spline_find_coeffs spline_info spline_order split_restart_file s_preconditioner s_quantum_numbers standard_orientation 
syn keyword cp2kKeyword start_coeffs start_elem start_index start_step start_step_in start_step_out states state_search state_type static steps 
syn keyword cp2kKeyword stepsize step_size step_start_val sto_ng stop_on_mismatch storage_location strength stress_tensor stride sub_box 
syn keyword cp2kKeyword subcells subcommunicators sub_conf subset_type surf_direction swap_probability sw_confidence_limit switch_coeff_state 
syn keyword cp2kKeyword switch_contraction_state switch_exp_state switch_set_state symmetric symmetry symmetry_elements t0 tamcsteps target 
syn keyword cp2kKeyword target_growth target_limit target_pot_semicore target_pot_valence target_pot_virtual targets task_type tau_cutoff 
syn keyword cp2kKeyword t_c_g_data temp tempdist_init_width tempdist_update_height tempdist_update_width temperature temperature_init temp_fast 
syn keyword cp2kKeyword temp_kind temp_slow tempstep_base tempstep_max temp_tol temp_tol_fast temp_tol_slow temp_tol_steps theta0 thread 
syn keyword cp2kKeyword threshold th_torb timecon timecon_langevin timecon_nh time_cumul time_start_val timestep tolerance total_density trace 
syn keyword cp2kKeyword trace_master trace_max trace_routines traj_file_name transa transb transformation treat_forces_in_core 
syn keyword cp2kKeyword treat_lsd_in_core truncation_radius trust_radius tshpsc_data t_tol typ_center type type_of_constraint type_of_density 
syn keyword cp2kKeyword uff_force_field uks u_minus_j unique_spline unit units u_ramping use_colvars use_comm_thread use_condition_number 
syn keyword cp2kKeyword use_exp use_finer_grid use_g96_velocity use_geep_lib use_history use_model_hessian use_mpi_allocation 
syn keyword cp2kKeyword use_old_gauge_atom use_plumed use_rat_fun_opt use_scf_energy_info util_info value values variable variables 
syn keyword cp2kKeyword variable_volume vdw_scale14 velocity_quench velocity_scale verbose_output verlet_skin virial virial_temps 
syn keyword cp2kKeyword vn_confidence_limit volume volume_isotropic vr0 vshock wait_time walker_comm_frequency walker_id walkers_status 
syn keyword cp2kKeyword wall_skin walltime wanted_proj_gradient wanted_rel_f_error wavelength weight weight_electron_configuration 
syn keyword cp2kKeyword weighting_function weight_method weight_pot_node weight_pot_semicore weight_pot_valence weight_pot_virtual weight_psir0 
syn keyword cp2kKeyword weights well_tempered wfn_restart_file_name width window_size w_matrix w_matrix_aux_fit worker_per_minima write_cube 
syn keyword cp2kKeyword write_frequency wtgamma ww xa xas_scf xc_deriv xc_smooth_rho xes_core x_hi x_low xrange xrd_interface xtl_info xyz 
syn keyword cp2kKeyword xyz_info y_hi y_low yoshida yrange zbl_scattering z_cutoff z_hi z_low zmp_constraint zora_type zrange

"----------------------------------------------------------------/
"       cp2k keywords alias
"----------------------------------------------------------------/
" grep -A2 -i "<Keyword" cp2k_input.xml | grep -i alias | sed 's;<NAME\s*type="alias">;;g' | sed 's;<\/NAME>;;g' | tr -d [:blank:] | tr '[:upper:]' '[:lower:]' | sort | uniq | xargs | fold -s -c -w 120 | sed -e 's/.*/syn keyword cp2kKeywordAlias &/'; echo
syn keyword cp2kKeywordAlias alpha alpha0_h ang angles at_list atomic_mass atoms_lu auxiliary_basis_fit_normalization auxiliary_basis_normalization 
syn keyword cp2kKeywordAlias auxiliary_basis_set auxiliary_fit_basis_set binary_restart_file calc_condition_number cg_points cg_width charge_b 
syn keyword cp2kKeywordAlias charge_o clebsch col_block_size connectivity conn_file conv coord_file coordinate core cubes_lu cutoff_list 
syn keyword cp2kKeywordAlias diagonalization_method dihedral dip_form di_rel dis dispersion_functional do_kernel dri eigvals eigvecs eip-model 
syn keyword cp2kKeywordAlias elec_temp element_symbol eps_fit eps_gvg eps_iso eps_lumos eps_num_deriv eps_scf_hist eps_storage eps_svd epstaylor 
syn keyword cp2kKeywordAlias epsvrho0 expon_denominator expon_denominatora expon_denominatorb expon_denominator_b expon_numerator expon_numeratora 
syn keyword cp2kKeywordAlias expon_numeratorb expon_numerator_b external_file fist_charge_scale f_roks interpolation invert_overlap iolevel k k2 k4 
syn keyword cp2kKeywordAlias l lambda laplace_group_size laplace_num_quad_points line_search link lmaxrho0 lmaxrho1 lri_basis lshift m mass 
syn keyword cp2kKeywordAlias max_cg_width max_diis_buffer_size maxiter max_iter_lumos max_jobs max_num_iter max_scf_hist max_vectors message_size 
syn keyword cp2kKeywordAlias minimizer mm mm1 mm2 mol mo_range multip multiple_time_steps n n_0 natoms ndiis n_ev ngroup nhtest noisygamma npulay 
syn keyword cp2kKeywordAlias n_reortho n_restarts nsimplemix nskip_mixing number_proc occnums orbital_basis_normalization orbital_basis_set 
syn keyword cp2kKeywordAlias orbital_eigenvalues_correction parmfile point point_point points points_from points_plane points_to points_to_b poisson 
syn keyword cp2kKeywordAlias pos pos_scaled pot pot_name precond program project protein qm q_maximum qmmm_charge_scale qmmm_coupling r_0 r_0_b ref 
syn keyword cp2kKeywordAlias ref_point relative_cutoff relax_multip restart_file_name restricted_excitations_type restricted_open_kohn_sham 
syn keyword cp2kKeywordAlias ri_mp2_basis_set rng r_oh roks_parameter roll_tol r_oo row_block_size rpa_group_size rpa_num_quad_points safer_diis 
syn keyword cp2kKeywordAlias segname shadowgamma shake_tol shell temp_to type unrestricted_kohn_sham v_shock wallti width xas_method

"----------------------------------------------------------------------------/
" fun stuff folding
"----------------------------------------------------------------------------/
syn region cp2kFold start="^\s*&\z(\w*\)"  end="^\s*&End\s\+\z1\>"  contains=cp2kFold fold keepend


"----------------------------------------------------------------/
"       cp2k numbers used in blocks
"----------------------------------------------------------------/
"   Regular int like number with - + or nothing in front
"       e.g. 918, or -49

syn match cp2kNumber '\d\+'
syn match cp2kNumber '[-+]\d\+'

"   Floating point number with decimal no E or e (+,-)
"       e.g. 0.198781, or -3.141592

syn match cp2kNumber '\d\+\.\d*'
syn match cp2kNumber '[-+]\d\+\.\d*'

"   Floating point like number with E and no decimal point (+,-)
"       e.g.    3E+9, 3e+09, or -3e+02

syn match cp2kNumber '[-+]\=\d[[:digit:]]*[eE][\-+]\=\d\+'
syn match cp2kNumber '\d[[:digit:]]*[eE][\-+]\=\d\+'

"   Floating point like number with E and decimal point (+,-)
"       e.g.    -3.9188e+09, or 0.9188E-93

syn match cp2kNumber '[-+]\=\d[[:digit:]]*\.\d*[eE][\-+]\=\d\+'
syn match cp2kNumber '\d[[:digit:]]*\.\d*[eE][\-+]\=\d\+'

syn keyword cp2kBool true false T F yes no


"-----------------------------------------------------------------/
"   CP2K comments
"-----------------------------------------------------------------/
syn keyword cp2kTodo TODO FIXME NOTE REMARK
syn match cp2kComment "#.*$" contains=cp2kTodo
syn match cp2kComment "!.*$" contains=cp2kTodo


"-----------------------------------------------------------------/
"   CP2K preprocessing directives
"-----------------------------------------------------------------/

syn match cp2kPreProc "@include"
syn match cp2kPreProc "@set"
syn match cp2kPreProc "@if"
syn match cp2kPreProc "@endif"



syn match cp2kBegSection /^[\ ]*&[a-zA-Z0-9_]\+/ contains=cp2kSection nextgroup=test
syn match test ".*[^!#]" contains=cp2kConstant,cp2kNumber,cp2kBool,cp2kComment,cp2kSection



syn match cp2kBegKeyword /^[\ ]*[a-zA-Z0-9_]\+/ contains=cp2kKeyword,cp2kKeywordAlias
syn match cp2kBegSection /^[\ ]*&[a-zA-Z0-9_]\+/ contains=cp2kSection


"----------------------------------------------------------------------------/
"   Final setup
"----------------------------------------------------------------------------/

let b:current_syntax = "cp2k"
set fdm=syntax
set foldlevel=3
"----------------------------------------------------------------------------/
"   cp2k keyword highlighting rules
"----------------------------------------------------------------------------/

hi def link cp2kComment Comment
hi def link cp2kTodo Todo
hi def link cp2kBool Boolean
hi def link cp2kNumber Boolean
hi def link cp2kSection Special
hi def link cp2kBegSection Special
hi def link cp2kEndSection Special
hi def link cp2kKeyword Statement
hi def link cp2kKeywordAlias Comment
hi def link cp2kConstant Constant
hi def link cp2kPreProc PreProc

