#
# This file was created by generate_dockerfiles.py.
# Usage: ./spack_cache_start.sh; podman build --network=host --shm-size=1g -f ./Dockerfile.test_spack_psmp-rockylinux ../../
#

ARG BASE_IMAGE="rockylinux:9.3"

###### Stage 1: Build CP2K ######

FROM "${BASE_IMAGE}" AS build_cp2k

RUN dnf -y install dnf-plugins-core && \
    dnf --enablerepo=crb -qy install \
    bzip2 \
    cmake \
    gcc gcc-c++ gcc-fortran \
    git \
    libtool \
    openssl-devel \
    patch \
    python3.11 \
    python3.11-devel \
    python3.11-pip \
    unzip \
    wget \
    xz \
    zlib-devel \
    zlib-static \
    && dnf clean -q all

RUN alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 2

ARG SPACK_CACHE="s3://spack-cache --s3-endpoint-url=http://localhost:9000"

# Copy CP2K repository into container
WORKDIR /opt
COPY . cp2k/

# Build CP2K dependencies
WORKDIR /opt/cp2k
RUN ./make_cp2k.sh -bd_only -cv psmp -gpu none -gv 11 -mpi mpich -ue -df libxsmm -ef openpmd

# Build and install CP2K
RUN ./make_cp2k.sh -cv psmp -gv 11 -gpu none -mpi mpich -df libxsmm -ef openpmd

###### Stage 2: Install CP2K ######

FROM "${BASE_IMAGE}" AS install_cp2k

RUN dnf -y install dnf-plugins-core && \
    dnf --enablerepo=crb -qy install \
    gcc gcc-c++ gcc-fortran \
    python3.11 \
    python3.11-pip \
    && dnf clean -q all

RUN alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 2

WORKDIR /opt/cp2k

# Install CP2K dependencies built with spack
COPY --from=build_cp2k /opt/cp2k/spack/spack/opt/spack ./spack/spack/opt/spack

# Install CP2K
COPY --from=build_cp2k /opt/cp2k/install ./install

# Install CP2K regression tests
COPY --from=build_cp2k /opt/cp2k/tests ./tests
COPY --from=build_cp2k /opt/cp2k/src/grid/sample_tasks ./src/grid/sample_tasks

# Install CP2K/Quickstep CI benchmarks
COPY --from=build_cp2k /opt/cp2k/benchmarks/CI ./benchmarks/CI

# Run CP2K regression test
RUN /opt/cp2k/install/bin/launch /opt/cp2k/install/bin/run_tests 

# Create entrypoint and finalise container build
WORKDIR /mnt
ENTRYPOINT ["/opt/cp2k/install/bin/launch"]
CMD ["cp2k", "--help", "--version"]
