ARG TOOLCHAIN=cp2k/toolchain:latest
FROM ${TOOLCHAIN}

# author: Ole Schuett

WORKDIR /workspace

COPY ./scripts/install_basics.sh .
RUN ./install_basics.sh

# Some buggy Python packages open utf8 files in text mode.
# As workaround we set locale.getpreferredencoding() to utf8.
ENV LANG="en_US.UTF-8" LANGUAGE="en_US:en" LC_ALL="en_US.UTF-8"

COPY ./scripts/install_aiida.sh .
RUN ./install_aiida.sh

COPY ./scripts/ci_entrypoint.sh ./scripts/test_aiida.sh ./
CMD ["./ci_entrypoint.sh", "./test_aiida.sh"]

#EOF
