ARG TOOLCHAIN=cp2k/toolchain:latest
FROM ${TOOLCHAIN}

# author: Ole Schuett

WORKDIR /workspace

COPY ./scripts/install_basics.sh .
RUN ./install_basics.sh

COPY ./scripts/install_performance.sh .
RUN ./install_performance.sh "local_cuda"

COPY ./scripts/ci_entrypoint.sh \
     ./scripts/test_performance.sh  \
     ./scripts/plot_performance.py  \
     ./

CMD ["./ci_entrypoint.sh", "./test_performance.sh", "local_cuda"]

#EOF
