#
# This file was created by generate_dockerfiles.py.
# Usage: docker build -f ./Dockerfile.test_doxygen ../../
#

FROM ubuntu:20.04

# Install test for doxygen.
WORKDIR /workspace

COPY ./tools/docker/scripts/install_basics.sh .
RUN ./install_basics.sh

COPY ./tools/docker/scripts/install_doxygen.sh .
RUN ./install_doxygen.sh

COPY ./tools/docker/scripts/ci_entrypoint.sh ./tools/docker/scripts/test_doxygen.sh ./
CMD ["./ci_entrypoint.sh", "./test_doxygen.sh"]

#EOF
