#
# This file was created by generate_dockerfiles.py.
# Usage: ./spack_cache_start.sh; podman build --network=host --shm-size=1g -f ./Dockerfile.test_spack_ssmp ../../
#

FROM "ubuntu:24.04"

RUN apt-get update -qq && apt-get install -qq --no-install-recommends \
    bzip2 \
    ca-certificates \
    cmake \
    g++-13 \
    gcc-13 \
    gfortran-13 \
    git \
    gnupg \
    libssh-dev \
    libssl-dev \
    libtool \
    libtool-bin \
    lsb-release \
    make \
    ninja-build \
    patch \
    pkgconf \
    python3 \
    python3-dev \
    python3-pip \
    python3-venv \
    unzip \
    wget \
    xxd \
    xz-utils \
    zstd \
    && rm -rf /var/lib/apt/lists/*

# Create links in /usr/local/bin to override tbe links in /usr/bin
RUN ln -sf /usr/bin/gcc-13      /usr/local/bin/gcc  && \
    ln -sf /usr/bin/g++-13      /usr/local/bin/g++  && \
    ln -sf /usr/bin/gfortran-13 /usr/local/bin/gfortran

ARG SPACK_CACHE="s3://spack-cache --s3-endpoint-url=http://localhost:9000"

# Copy CP2K repository into container
WORKDIR /opt
COPY . cp2k/

# Build and install CP2K
WORKDIR /opt/cp2k
RUN /bin/bash -o pipefail -c "source ./make_cp2k.sh -cv ssmp -mpi no -t \"\""

# Finalise container build
WORKDIR /mnt
ENTRYPOINT ["/opt/cp2k/install/bin/entrypoint.sh"]
CMD ["cp2k", "--help"]
