#
# This file was created by generate_dockerfiles.py.
# Usage: docker build -f ./Dockerfile.test_python ../../
#

FROM ubuntu:20.04

# Install test for python.
WORKDIR /workspace

COPY ./tools/docker/scripts/install_basics.sh .
RUN ./install_basics.sh

COPY ./tools/docker/scripts/install_python.sh .
RUN ./install_python.sh

COPY ./tools/docker/scripts/ci_entrypoint.sh ./tools/docker/scripts/test_python.sh ./
CMD ["./ci_entrypoint.sh", "./test_python.sh"]

#EOF
