FROM ubuntu:18.04

# author: Ole Schuett

WORKDIR /workspace

COPY ./scripts/install_basics.sh .
RUN ./install_basics.sh

# set a proper unicode-enabled locale, see https://hub.docker.com/_/ubuntu?tab=description
RUN localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.UTF-8

COPY ./scripts/install_formatting.sh .
RUN ./install_formatting.sh

COPY ./scripts/ci_entrypoint.sh ./scripts/test_formatting.sh ./
CMD ["./ci_entrypoint.sh", "./test_formatting.sh"]

#EOF
